package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.AccountAttribute;
import cj.studio.backend.uc.bo.AccountAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	long countByExample(AccountAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int deleteByExample(AccountAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int insert(AccountAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int insertSelective(AccountAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	List<AccountAttribute> selectByExample(AccountAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	AccountAttribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByExampleSelective(@Param("record") AccountAttribute record,
			@Param("example") AccountAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByExample(@Param("record") AccountAttribute record, @Param("example") AccountAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByPrimaryKeySelective(AccountAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountattr
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByPrimaryKey(AccountAttribute record);
}