package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.AppAttribute;
import cj.studio.backend.uc.bo.AppAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	long countByExample(AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int deleteByExample(AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int insert(AppAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int insertSelective(AppAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	List<AppAttribute> selectByExample(AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	AppAttribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByExampleSelective(@Param("record") AppAttribute record, @Param("example") AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByExample(@Param("record") AppAttribute record, @Param("example") AppAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByPrimaryKeySelective(AppAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByPrimaryKey(AppAttribute record);
}