package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.AppSegment;
import cj.studio.backend.uc.bo.AppSegmentExample;
import cj.studio.backend.uc.bo.Segment;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppSegmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	long countByExample(AppSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int deleteByExample(AppSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int insert(AppSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int insertSelective(AppSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	List<AppSegment> selectByExample(AppSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	AppSegment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByExampleSelective(@Param("record") AppSegment record, @Param("example") AppSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByExample(@Param("record") AppSegment record, @Param("example") AppSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByPrimaryKeySelective(AppSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table appseg
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByPrimaryKey(AppSegment record);

	List<Segment> getSegments(@Param(value="appCode")String appCode);

}