package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.Attribute;
import cj.studio.backend.uc.bo.AttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	long countByExample(AttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int deleteByExample(AttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int insert(Attribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int insertSelective(Attribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	List<Attribute> selectByExample(AttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	Attribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Attribute record, @Param("example") AttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByExample(@Param("record") Attribute record, @Param("example") AttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByPrimaryKeySelective(Attribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table attribute
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByPrimaryKey(Attribute record);
}