package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.CompanyAttribute;
import cj.studio.backend.uc.bo.CompanyAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	long countByExample(CompanyAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int deleteByExample(CompanyAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int insert(CompanyAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int insertSelective(CompanyAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	List<CompanyAttribute> selectByExample(CompanyAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	CompanyAttribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByExampleSelective(@Param("record") CompanyAttribute record,
			@Param("example") CompanyAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByExample(@Param("record") CompanyAttribute record, @Param("example") CompanyAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByPrimaryKeySelective(CompanyAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table companyattr
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByPrimaryKey(CompanyAttribute record);
}