package cj.studio.backend.uc.plugin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cj.studio.backend.uc.bo.GlobalRole;
import cj.studio.backend.uc.bo.GlobalRoleExample;

public interface GlobalRoleMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	long countByExample(GlobalRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int deleteByExample(GlobalRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int insert(GlobalRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int insertSelective(GlobalRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	List<GlobalRole> selectByExample(GlobalRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	GlobalRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByExampleSelective(@Param("record") GlobalRole record, @Param("example") GlobalRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByExample(@Param("record") GlobalRole record, @Param("example") GlobalRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByPrimaryKeySelective(GlobalRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table globalrole
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	int updateByPrimaryKey(GlobalRole record);

	List<GlobalRole> getPage(@Param(value="currPage")int currPage, @Param(value="pageSize")int pageSize);
}