package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.Organization;
import cj.studio.backend.uc.bo.OrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	long countByExample(OrganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int deleteByExample(OrganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int insert(Organization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int insertSelective(Organization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	List<Organization> selectByExample(OrganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	Organization selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByExample(@Param("record") Organization record, @Param("example") OrganizationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByPrimaryKeySelective(Organization record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table organization
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByPrimaryKey(Organization record);

	List<Organization> getPage(@Param(value="currPage")int currPage, @Param(value="pageSize")int pageSize);
}