package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.OrgAttribute;
import cj.studio.backend.uc.bo.OrgAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgAttributeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	long countByExample(OrgAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int deleteByExample(OrgAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int insert(OrgAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int insertSelective(OrgAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	List<OrgAttribute> selectByExample(OrgAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	OrgAttribute selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByExampleSelective(@Param("record") OrgAttribute record, @Param("example") OrgAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByExample(@Param("record") OrgAttribute record, @Param("example") OrgAttributeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByPrimaryKeySelective(OrgAttribute record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgattr
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	int updateByPrimaryKey(OrgAttribute record);
}