package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.OrgSegment;
import cj.studio.backend.uc.bo.OrgSegmentExample;
import cj.studio.backend.uc.bo.Segment;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrgSegmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	long countByExample(OrgSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int deleteByExample(OrgSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int insert(OrgSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int insertSelective(OrgSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	List<OrgSegment> selectByExample(OrgSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	OrgSegment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByExampleSelective(@Param("record") OrgSegment record, @Param("example") OrgSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByExample(@Param("record") OrgSegment record, @Param("example") OrgSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByPrimaryKeySelective(OrgSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orgseg
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	int updateByPrimaryKey(OrgSegment record);

	List<Segment> getSegments(@Param(value="orgCode")String orgCode);
}