package cj.studio.backend.uc.plugin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cj.studio.backend.uc.bo.Segment;
import cj.studio.backend.uc.bo.TenantSegment;
import cj.studio.backend.uc.bo.TenantSegmentExample;

public interface TenantSegmentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	long countByExample(TenantSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int deleteByExample(TenantSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int insert(TenantSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int insertSelective(TenantSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	List<TenantSegment> selectByExample(TenantSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	TenantSegment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int updateByExampleSelective(@Param("record") TenantSegment record, @Param("example") TenantSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int updateByExample(@Param("record") TenantSegment record, @Param("example") TenantSegmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int updateByPrimaryKeySelective(TenantSegment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantseg
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	int updateByPrimaryKey(TenantSegment record);

	List<Segment> getSegments(@Param(value="tenantCode")String tenantCode);
}