package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.TenantPost;
import cj.studio.backend.uc.bo.TenantPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TenantPostMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	long countByExample(TenantPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int deleteByExample(TenantPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int insert(TenantPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int insertSelective(TenantPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	List<TenantPost> selectByExample(TenantPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	TenantPost selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int updateByExampleSelective(@Param("record") TenantPost record, @Param("example") TenantPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int updateByExample(@Param("record") TenantPost record, @Param("example") TenantPostExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int updateByPrimaryKeySelective(TenantPost record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantpost
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	int updateByPrimaryKey(TenantPost record);

	List<TenantPost> pagePost(@Param("tenantCode") String tenantCode, @Param("currPage") int currPage,
			@Param("pageSize") int pageSize);
}