package cj.studio.backend.uc.plugin.dao;

import cj.studio.backend.uc.bo.TenantRole;
import cj.studio.backend.uc.bo.TenantRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TenantRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	long countByExample(TenantRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int deleteByExample(TenantRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int insert(TenantRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int insertSelective(TenantRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	List<TenantRole> selectByExample(TenantRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	TenantRole selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByExampleSelective(@Param("record") TenantRole record, @Param("example") TenantRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByExample(@Param("record") TenantRole record, @Param("example") TenantRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByPrimaryKeySelective(TenantRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenantrole
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	int updateByPrimaryKey(TenantRole record);

	List<TenantRole> page(@Param("tenantCode") String tenantCode, @Param("currPage") int currPage,
			@Param("pageSize") int pageSize);
}