package cj.studio.backend.uc.bo;

import java.util.ArrayList;
import java.util.List;

public class AccountSegmentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public AccountSegmentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTenantcodeIsNull() {
			addCriterion("tenantCode is null");
			return (Criteria) this;
		}

		public Criteria andTenantcodeIsNotNull() {
			addCriterion("tenantCode is not null");
			return (Criteria) this;
		}

		public Criteria andTenantcodeEqualTo(String value) {
			addCriterion("tenantCode =", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeNotEqualTo(String value) {
			addCriterion("tenantCode <>", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeGreaterThan(String value) {
			addCriterion("tenantCode >", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeGreaterThanOrEqualTo(String value) {
			addCriterion("tenantCode >=", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeLessThan(String value) {
			addCriterion("tenantCode <", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeLessThanOrEqualTo(String value) {
			addCriterion("tenantCode <=", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeLike(String value) {
			addCriterion("tenantCode like", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeNotLike(String value) {
			addCriterion("tenantCode not like", value, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeIn(List<String> values) {
			addCriterion("tenantCode in", values, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeNotIn(List<String> values) {
			addCriterion("tenantCode not in", values, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeBetween(String value1, String value2) {
			addCriterion("tenantCode between", value1, value2, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andTenantcodeNotBetween(String value1, String value2) {
			addCriterion("tenantCode not between", value1, value2, "tenantcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeIsNull() {
			addCriterion("segCode is null");
			return (Criteria) this;
		}

		public Criteria andSegcodeIsNotNull() {
			addCriterion("segCode is not null");
			return (Criteria) this;
		}

		public Criteria andSegcodeEqualTo(String value) {
			addCriterion("segCode =", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeNotEqualTo(String value) {
			addCriterion("segCode <>", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeGreaterThan(String value) {
			addCriterion("segCode >", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeGreaterThanOrEqualTo(String value) {
			addCriterion("segCode >=", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeLessThan(String value) {
			addCriterion("segCode <", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeLessThanOrEqualTo(String value) {
			addCriterion("segCode <=", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeLike(String value) {
			addCriterion("segCode like", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeNotLike(String value) {
			addCriterion("segCode not like", value, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeIn(List<String> values) {
			addCriterion("segCode in", values, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeNotIn(List<String> values) {
			addCriterion("segCode not in", values, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeBetween(String value1, String value2) {
			addCriterion("segCode between", value1, value2, "segcode");
			return (Criteria) this;
		}

		public Criteria andSegcodeNotBetween(String value1, String value2) {
			addCriterion("segCode not between", value1, value2, "segcode");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("sort is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("sort is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("sort =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("sort <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("sort >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("sort >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("sort <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("sort <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("sort in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("sort not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("sort between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("sort not between", value1, value2, "sort");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table accountseg
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table accountseg
     *
     * @mbg.generated do_not_delete_during_merge Tue May 07 09:38:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}