package cj.studio.backend.uc.bo;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.code
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.tenantCode
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    private String tenantcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.userCode
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    private String usercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.face
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    private String face;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.code
     *
     * @return the value of account.code
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.code
     *
     * @param code the value for account.code
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.tenantCode
     *
     * @return the value of account.tenantCode
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public String getTenantcode() {
        return tenantcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.tenantCode
     *
     * @param tenantcode the value for account.tenantCode
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public void setTenantcode(String tenantcode) {
        this.tenantcode = tenantcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.userCode
     *
     * @return the value of account.userCode
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.userCode
     *
     * @param usercode the value for account.userCode
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.face
     *
     * @return the value of account.face
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.face
     *
     * @param face the value for account.face
     *
     * @mbg.generated Tue May 07 18:57:16 CST 2019
     */
    public void setFace(String face) {
        this.face = face;
    }
}