package cj.studio.backend.uc.bo;

public class Account {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.code
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.appCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String appcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.name
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account.face
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String face;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.id
	 * @return  the value of account.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.id
	 * @param id  the value for account.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.code
	 * @return  the value of account.code
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.code
	 * @param code  the value for account.code
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.appCode
	 * @return  the value of account.appCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getAppcode() {
		return appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.appCode
	 * @param appcode  the value for account.appCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.name
	 * @return  the value of account.name
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.name
	 * @param name  the value for account.name
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account.face
	 * @return  the value of account.face
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getFace() {
		return face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account.face
	 * @param face  the value for account.face
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setFace(String face) {
		this.face = face;
	}
}