package cj.studio.backend.uc.bo;

public class AccountAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accountattr.id
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accountattr.accountCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String accountcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accountattr.tenantCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String tenantcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accountattr.attrCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String attrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accountattr.segCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column accountattr.value
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accountattr.id
	 * @return  the value of accountattr.id
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accountattr.id
	 * @param id  the value for accountattr.id
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accountattr.accountCode
	 * @return  the value of accountattr.accountCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getAccountcode() {
		return accountcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accountattr.accountCode
	 * @param accountcode  the value for accountattr.accountCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setAccountcode(String accountcode) {
		this.accountcode = accountcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accountattr.tenantCode
	 * @return  the value of accountattr.tenantCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getTenantcode() {
		return tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accountattr.tenantCode
	 * @param tenantcode  the value for accountattr.tenantCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setTenantcode(String tenantcode) {
		this.tenantcode = tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accountattr.attrCode
	 * @return  the value of accountattr.attrCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getAttrcode() {
		return attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accountattr.attrCode
	 * @param attrcode  the value for accountattr.attrCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setAttrcode(String attrcode) {
		this.attrcode = attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accountattr.segCode
	 * @return  the value of accountattr.segCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accountattr.segCode
	 * @param segcode  the value for accountattr.segCode
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column accountattr.value
	 * @return  the value of accountattr.value
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column accountattr.value
	 * @param value  the value for accountattr.value
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setValue(String value) {
		this.value = value;
	}
}