package cj.studio.backend.uc.bo;

public class App {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.code
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.name
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.href
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.icon
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.tips
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private String tips;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.comment
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.id
     *
     * @return the value of app.id
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.id
     *
     * @param id the value for app.id
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.code
     *
     * @return the value of app.code
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.code
     *
     * @param code the value for app.code
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.name
     *
     * @return the value of app.name
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.name
     *
     * @param name the value for app.name
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.href
     *
     * @return the value of app.href
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.href
     *
     * @param href the value for app.href
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.icon
     *
     * @return the value of app.icon
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.icon
     *
     * @param icon the value for app.icon
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.tips
     *
     * @return the value of app.tips
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.tips
     *
     * @param tips the value for app.tips
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setTips(String tips) {
        this.tips = tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.comment
     *
     * @return the value of app.comment
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.comment
     *
     * @param comment the value for app.comment
     *
     * @mbg.generated Thu Jul 04 12:56:50 CST 2019
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}