package cj.studio.backend.uc.bo;

public class AppAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appattr.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appattr.appCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String appcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appattr.attrCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String attrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appattr.segCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appattr.value
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appattr.id
	 * @return  the value of appattr.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appattr.id
	 * @param id  the value for appattr.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appattr.appCode
	 * @return  the value of appattr.appCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getAppcode() {
		return appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appattr.appCode
	 * @param appcode  the value for appattr.appCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appattr.attrCode
	 * @return  the value of appattr.attrCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getAttrcode() {
		return attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appattr.attrCode
	 * @param attrcode  the value for appattr.attrCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setAttrcode(String attrcode) {
		this.attrcode = attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appattr.segCode
	 * @return  the value of appattr.segCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appattr.segCode
	 * @param segcode  the value for appattr.segCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appattr.value
	 * @return  the value of appattr.value
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appattr.value
	 * @param value  the value for appattr.value
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setValue(String value) {
		this.value = value;
	}
}