package cj.studio.backend.uc.bo;

public class Application {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column application.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column application.appCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String appcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column application.appName
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String appname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column application.createTime
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private Long createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column application.id
	 * @return  the value of application.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column application.id
	 * @param id  the value for application.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column application.appCode
	 * @return  the value of application.appCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getAppcode() {
		return appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column application.appCode
	 * @param appcode  the value for application.appCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column application.appName
	 * @return  the value of application.appName
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getAppname() {
		return appname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column application.appName
	 * @param appname  the value for application.appName
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setAppname(String appname) {
		this.appname = appname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column application.createTime
	 * @return  the value of application.createTime
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public Long getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column application.createTime
	 * @param createtime  the value for application.createTime
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}
}