package cj.studio.backend.uc.bo;

public class AppSegment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appseg.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appseg.appCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String appcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appseg.segCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column appseg.sort
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appseg.id
	 * @return  the value of appseg.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appseg.id
	 * @param id  the value for appseg.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appseg.appCode
	 * @return  the value of appseg.appCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getAppcode() {
		return appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appseg.appCode
	 * @param appcode  the value for appseg.appCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appseg.segCode
	 * @return  the value of appseg.segCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appseg.segCode
	 * @param segcode  the value for appseg.segCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column appseg.sort
	 * @return  the value of appseg.sort
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column appseg.sort
	 * @param sort  the value for appseg.sort
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}