package cj.studio.backend.uc.bo;

public class Attribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.code
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.name
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.type
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.segCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attribute.sort
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.id
	 * @return  the value of attribute.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.id
	 * @param id  the value for attribute.id
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.code
	 * @return  the value of attribute.code
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.code
	 * @param code  the value for attribute.code
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.name
	 * @return  the value of attribute.name
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.name
	 * @param name  the value for attribute.name
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.type
	 * @return  the value of attribute.type
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.type
	 * @param type  the value for attribute.type
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.segCode
	 * @return  the value of attribute.segCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.segCode
	 * @param segcode  the value for attribute.segCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attribute.sort
	 * @return  the value of attribute.sort
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attribute.sort
	 * @param sort  the value for attribute.sort
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}