package cj.studio.backend.uc.bo;

public class CompanySegment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyseg.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyseg.tenantCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String tenantcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyseg.segCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyseg.sort
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyseg.id
	 * @return  the value of companyseg.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyseg.id
	 * @param id  the value for companyseg.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyseg.tenantCode
	 * @return  the value of companyseg.tenantCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getTenantcode() {
		return tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyseg.tenantCode
	 * @param tenantcode  the value for companyseg.tenantCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setTenantcode(String tenantcode) {
		this.tenantcode = tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyseg.segCode
	 * @return  the value of companyseg.segCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyseg.segCode
	 * @param segcode  the value for companyseg.segCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyseg.sort
	 * @return  the value of companyseg.sort
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyseg.sort
	 * @param sort  the value for companyseg.sort
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}