package cj.studio.backend.uc.bo;

public class Company {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.id
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.code
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.cnname
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String cnname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.enname
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String enname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.ctime
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private Long ctime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.id
	 * @return  the value of company.id
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.id
	 * @param id  the value for company.id
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.code
	 * @return  the value of company.code
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.code
	 * @param code  the value for company.code
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.cnname
	 * @return  the value of company.cnname
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getCnname() {
		return cnname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.cnname
	 * @param cnname  the value for company.cnname
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setCnname(String cnname) {
		this.cnname = cnname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.enname
	 * @return  the value of company.enname
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getEnname() {
		return enname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.enname
	 * @param enname  the value for company.enname
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setEnname(String enname) {
		this.enname = enname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.ctime
	 * @return  the value of company.ctime
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public Long getCtime() {
		return ctime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.ctime
	 * @param ctime  the value for company.ctime
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setCtime(Long ctime) {
		this.ctime = ctime;
	}
}