package cj.studio.backend.uc.bo;

public class CompanyAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyattr.id
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyattr.companyCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String companycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyattr.segCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyattr.attrCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String attrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column companyattr.value
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyattr.id
	 * @return  the value of companyattr.id
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyattr.id
	 * @param id  the value for companyattr.id
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyattr.companyCode
	 * @return  the value of companyattr.companyCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getCompanycode() {
		return companycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyattr.companyCode
	 * @param companycode  the value for companyattr.companyCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setCompanycode(String companycode) {
		this.companycode = companycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyattr.segCode
	 * @return  the value of companyattr.segCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyattr.segCode
	 * @param segcode  the value for companyattr.segCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyattr.attrCode
	 * @return  the value of companyattr.attrCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getAttrcode() {
		return attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyattr.attrCode
	 * @param attrcode  the value for companyattr.attrCode
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setAttrcode(String attrcode) {
		this.attrcode = attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column companyattr.value
	 * @return  the value of companyattr.value
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column companyattr.value
	 * @param value  the value for companyattr.value
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setValue(String value) {
		this.value = value;
	}
}