package cj.studio.backend.uc.bo;

public class GlobalRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column globalrole.id
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column globalrole.code
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column globalrole.name
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column globalrole.comment
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column globalrole.id
	 * @return  the value of globalrole.id
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column globalrole.id
	 * @param id  the value for globalrole.id
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column globalrole.code
	 * @return  the value of globalrole.code
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column globalrole.code
	 * @param code  the value for globalrole.code
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column globalrole.name
	 * @return  the value of globalrole.name
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column globalrole.name
	 * @param name  the value for globalrole.name
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column globalrole.comment
	 * @return  the value of globalrole.comment
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column globalrole.comment
	 * @param comment  the value for globalrole.comment
	 * @mbg.generated  Sat May 11 15:47:57 CST 2019
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}