package cj.studio.backend.uc.bo;

public class OrgAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgattr.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgattr.orgCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String orgcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgattr.segCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgattr.attrCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String attrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgattr.value
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgattr.id
	 * @return  the value of orgattr.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgattr.id
	 * @param id  the value for orgattr.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgattr.orgCode
	 * @return  the value of orgattr.orgCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getOrgcode() {
		return orgcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgattr.orgCode
	 * @param orgcode  the value for orgattr.orgCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgattr.segCode
	 * @return  the value of orgattr.segCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgattr.segCode
	 * @param segcode  the value for orgattr.segCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgattr.attrCode
	 * @return  the value of orgattr.attrCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getAttrcode() {
		return attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgattr.attrCode
	 * @param attrcode  the value for orgattr.attrCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setAttrcode(String attrcode) {
		this.attrcode = attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgattr.value
	 * @return  the value of orgattr.value
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgattr.value
	 * @param value  the value for orgattr.value
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setValue(String value) {
		this.value = value;
	}
}