package cj.studio.backend.uc.bo;

public class Organization {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.code
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.name
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.appCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String appcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column organization.pid
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String pid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.id
	 * @return  the value of organization.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.id
	 * @param id  the value for organization.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.code
	 * @return  the value of organization.code
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.code
	 * @param code  the value for organization.code
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.name
	 * @return  the value of organization.name
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.name
	 * @param name  the value for organization.name
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.appCode
	 * @return  the value of organization.appCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getAppcode() {
		return appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.appCode
	 * @param appcode  the value for organization.appCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setAppcode(String appcode) {
		this.appcode = appcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column organization.pid
	 * @return  the value of organization.pid
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column organization.pid
	 * @param pid  the value for organization.pid
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}
}