package cj.studio.backend.uc.bo;

public class OrgMemberRole extends OrgMemberRoleKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgmemrole.roleCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	private String rolecode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgmemrole.roleCode
	 * @return  the value of orgmemrole.roleCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public String getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgmemrole.roleCode
	 * @param rolecode  the value for orgmemrole.roleCode
	 * @mbg.generated  Sat Jan 12 13:47:21 CST 2019
	 */
	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}
}