package cj.studio.backend.uc.bo;

public class OrgSegment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgseg.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgseg.orgCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String orgcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgseg.segCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orgseg.sort
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	private Integer sort;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgseg.id
	 * @return  the value of orgseg.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgseg.id
	 * @param id  the value for orgseg.id
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgseg.orgCode
	 * @return  the value of orgseg.orgCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getOrgcode() {
		return orgcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgseg.orgCode
	 * @param orgcode  the value for orgseg.orgCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgseg.segCode
	 * @return  the value of orgseg.segCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgseg.segCode
	 * @param segcode  the value for orgseg.segCode
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orgseg.sort
	 * @return  the value of orgseg.sort
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orgseg.sort
	 * @param sort  the value for orgseg.sort
	 * @mbg.generated  Mon Jan 14 22:51:29 CST 2019
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}