package cj.studio.backend.uc.bo;

public class Segment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column segment.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column segment.code
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column segment.name
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column segment.createTime
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private Long createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column segment.version
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column segment.id
	 * @return  the value of segment.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column segment.id
	 * @param id  the value for segment.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column segment.code
	 * @return  the value of segment.code
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column segment.code
	 * @param code  the value for segment.code
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column segment.name
	 * @return  the value of segment.name
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column segment.name
	 * @param name  the value for segment.name
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column segment.createTime
	 * @return  the value of segment.createTime
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Long getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column segment.createTime
	 * @param createtime  the value for segment.createTime
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setCreatetime(Long createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column segment.version
	 * @return  the value of segment.version
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column segment.version
	 * @param version  the value for segment.version
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setVersion(String version) {
		this.version = version;
	}
}