package cj.studio.backend.uc.bo;

public class TenantPost {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantpost.id
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantpost.code
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantpost.name
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantpost.tenant
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String tenant;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantpost.comment
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantpost.id
	 * @return  the value of tenantpost.id
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantpost.id
	 * @param id  the value for tenantpost.id
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantpost.code
	 * @return  the value of tenantpost.code
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantpost.code
	 * @param code  the value for tenantpost.code
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantpost.name
	 * @return  the value of tenantpost.name
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantpost.name
	 * @param name  the value for tenantpost.name
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantpost.tenant
	 * @return  the value of tenantpost.tenant
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getTenant() {
		return tenant;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantpost.tenant
	 * @param tenant  the value for tenantpost.tenant
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setTenant(String tenant) {
		this.tenant = tenant;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantpost.comment
	 * @return  the value of tenantpost.comment
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantpost.comment
	 * @param comment  the value for tenantpost.comment
	 * @mbg.generated  Thu Jul 04 12:56:50 CST 2019
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}