package cj.studio.backend.uc.bo;

public class TenantGroup {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantgroup.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantgroup.code
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantgroup.name
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantgroup.tenant
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String tenant;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantgroup.comment
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String comment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantgroup.id
	 * @return  the value of tenantgroup.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantgroup.id
	 * @param id  the value for tenantgroup.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantgroup.code
	 * @return  the value of tenantgroup.code
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantgroup.code
	 * @param code  the value for tenantgroup.code
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantgroup.name
	 * @return  the value of tenantgroup.name
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantgroup.name
	 * @param name  the value for tenantgroup.name
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantgroup.tenant
	 * @return  the value of tenantgroup.tenant
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getTenant() {
		return tenant;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantgroup.tenant
	 * @param tenant  the value for tenantgroup.tenant
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setTenant(String tenant) {
		this.tenant = tenant;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantgroup.comment
	 * @return  the value of tenantgroup.comment
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantgroup.comment
	 * @param comment  the value for tenantgroup.comment
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}