package cj.studio.backend.uc.bo;

import java.util.ArrayList;
import java.util.List;

public class TenantExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public TenantExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andOwnercodeIsNull() {
			addCriterion("ownerCode is null");
			return (Criteria) this;
		}

		public Criteria andOwnercodeIsNotNull() {
			addCriterion("ownerCode is not null");
			return (Criteria) this;
		}

		public Criteria andOwnercodeEqualTo(String value) {
			addCriterion("ownerCode =", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeNotEqualTo(String value) {
			addCriterion("ownerCode <>", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeGreaterThan(String value) {
			addCriterion("ownerCode >", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeGreaterThanOrEqualTo(String value) {
			addCriterion("ownerCode >=", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeLessThan(String value) {
			addCriterion("ownerCode <", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeLessThanOrEqualTo(String value) {
			addCriterion("ownerCode <=", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeLike(String value) {
			addCriterion("ownerCode like", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeNotLike(String value) {
			addCriterion("ownerCode not like", value, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeIn(List<String> values) {
			addCriterion("ownerCode in", values, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeNotIn(List<String> values) {
			addCriterion("ownerCode not in", values, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeBetween(String value1, String value2) {
			addCriterion("ownerCode between", value1, value2, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnercodeNotBetween(String value1, String value2) {
			addCriterion("ownerCode not between", value1, value2, "ownercode");
			return (Criteria) this;
		}

		public Criteria andOwnertypeIsNull() {
			addCriterion("ownerType is null");
			return (Criteria) this;
		}

		public Criteria andOwnertypeIsNotNull() {
			addCriterion("ownerType is not null");
			return (Criteria) this;
		}

		public Criteria andOwnertypeEqualTo(String value) {
			addCriterion("ownerType =", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeNotEqualTo(String value) {
			addCriterion("ownerType <>", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeGreaterThan(String value) {
			addCriterion("ownerType >", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeGreaterThanOrEqualTo(String value) {
			addCriterion("ownerType >=", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeLessThan(String value) {
			addCriterion("ownerType <", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeLessThanOrEqualTo(String value) {
			addCriterion("ownerType <=", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeLike(String value) {
			addCriterion("ownerType like", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeNotLike(String value) {
			addCriterion("ownerType not like", value, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeIn(List<String> values) {
			addCriterion("ownerType in", values, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeNotIn(List<String> values) {
			addCriterion("ownerType not in", values, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeBetween(String value1, String value2) {
			addCriterion("ownerType between", value1, value2, "ownertype");
			return (Criteria) this;
		}

		public Criteria andOwnertypeNotBetween(String value1, String value2) {
			addCriterion("ownerType not between", value1, value2, "ownertype");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createTime is null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreatetimeEqualTo(Long value) {
			addCriterion("createTime =", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotEqualTo(Long value) {
			addCriterion("createTime <>", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThan(Long value) {
			addCriterion("createTime >", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Long value) {
			addCriterion("createTime >=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThan(Long value) {
			addCriterion("createTime <", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Long value) {
			addCriterion("createTime <=", value, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeIn(List<Long> values) {
			addCriterion("createTime in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotIn(List<Long> values) {
			addCriterion("createTime not in", values, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeBetween(Long value1, Long value2) {
			addCriterion("createTime between", value1, value2, "createtime");
			return (Criteria) this;
		}

		public Criteria andCreatetimeNotBetween(Long value1, Long value2) {
			addCriterion("createTime not between", value1, value2, "createtime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tenant
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tenant
     *
     * @mbg.generated do_not_delete_during_merge Tue May 07 09:38:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}