package cj.studio.backend.uc.bo;

public class TenantAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantattr.id
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantattr.tenantCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	private String tenantcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantattr.attrCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	private String attrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantattr.segCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenantattr.value
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantattr.id
	 * @return  the value of tenantattr.id
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantattr.id
	 * @param id  the value for tenantattr.id
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantattr.tenantCode
	 * @return  the value of tenantattr.tenantCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public String getTenantcode() {
		return tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantattr.tenantCode
	 * @param tenantcode  the value for tenantattr.tenantCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public void setTenantcode(String tenantcode) {
		this.tenantcode = tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantattr.attrCode
	 * @return  the value of tenantattr.attrCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public String getAttrcode() {
		return attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantattr.attrCode
	 * @param attrcode  the value for tenantattr.attrCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public void setAttrcode(String attrcode) {
		this.attrcode = attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantattr.segCode
	 * @return  the value of tenantattr.segCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantattr.segCode
	 * @param segcode  the value for tenantattr.segCode
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenantattr.value
	 * @return  the value of tenantattr.value
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenantattr.value
	 * @param value  the value for tenantattr.value
	 * @mbg.generated  Thu Apr 04 22:03:54 CST 2019
	 */
	public void setValue(String value) {
		this.value = value;
	}
}