package cj.studio.backend.uc.bo;

public class UA {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ua.id
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ua.userCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ua.colCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String colcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ua.colType
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String coltype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ua.tenantCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	private String tenantcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ua.id
	 * @return  the value of ua.id
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ua.id
	 * @param id  the value for ua.id
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ua.userCode
	 * @return  the value of ua.userCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ua.userCode
	 * @param usercode  the value for ua.userCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ua.colCode
	 * @return  the value of ua.colCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getColcode() {
		return colcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ua.colCode
	 * @param colcode  the value for ua.colCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setColcode(String colcode) {
		this.colcode = colcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ua.colType
	 * @return  the value of ua.colType
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getColtype() {
		return coltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ua.colType
	 * @param coltype  the value for ua.colType
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setColtype(String coltype) {
		this.coltype = coltype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ua.tenantCode
	 * @return  the value of ua.tenantCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public String getTenantcode() {
		return tenantcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ua.tenantCode
	 * @param tenantcode  the value for ua.tenantCode
	 * @mbg.generated  Tue May 07 18:57:16 CST 2019
	 */
	public void setTenantcode(String tenantcode) {
		this.tenantcode = tenantcode;
	}
}