package cj.studio.backend.uc.bo;

public class UserAttribute {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattr.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattr.userCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattr.segCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String segcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattr.attrCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String attrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userattr.value
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	private String value;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattr.id
	 * @return  the value of userattr.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattr.id
	 * @param id  the value for userattr.id
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattr.userCode
	 * @return  the value of userattr.userCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattr.userCode
	 * @param usercode  the value for userattr.userCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattr.segCode
	 * @return  the value of userattr.segCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getSegcode() {
		return segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattr.segCode
	 * @param segcode  the value for userattr.segCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setSegcode(String segcode) {
		this.segcode = segcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattr.attrCode
	 * @return  the value of userattr.attrCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getAttrcode() {
		return attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattr.attrCode
	 * @param attrcode  the value for userattr.attrCode
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setAttrcode(String attrcode) {
		this.attrcode = attrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userattr.value
	 * @return  the value of userattr.value
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userattr.value
	 * @param value  the value for userattr.value
	 * @mbg.generated  Fri May 10 19:03:13 CST 2019
	 */
	public void setValue(String value) {
		this.value = value;
	}
}