package cj.studio.backend.uc.bo;

public class UserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userrole.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userrole.userCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String usercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column userrole.roleCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	private String rolecode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userrole.id
	 * @return  the value of userrole.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userrole.id
	 * @param id  the value for userrole.id
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userrole.userCode
	 * @return  the value of userrole.userCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userrole.userCode
	 * @param usercode  the value for userrole.userCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column userrole.roleCode
	 * @return  the value of userrole.roleCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public String getRolecode() {
		return rolecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column userrole.roleCode
	 * @param rolecode  the value for userrole.roleCode
	 * @mbg.generated  Mon Jan 14 17:59:03 CST 2019
	 */
	public void setRolecode(String rolecode) {
		this.rolecode = rolecode;
	}
}